routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('categories', CategoryController::class);
    Route::get('products/search', [ProductController::class, 'search'])->name('products.search');
    Route::resource('products', ProductController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'image',
        'description',
        'quantity',
        'price'
    ];

    public function scopeSearch($query, $searchTerm, $limit = null)
    {
        $searchValue = '%' . $searchTerm . '%';
        return $query->with('categories')
            ->where('name', 'like', $searchValue)
            ->orWhere('price', 'like', $searchValue)
            ->orWhereHas('categories', function ($query) use ($searchValue) {
                $query->where('name', 'like', $searchValue);
            })
            ->paginate($limit);
    }

    public function getImageUrlAttribute()
    {
        return 'storage/images/'. (Storage::disk('public')->exists('/images/'.$this->image) ? $this->image : 'noImage.jpg');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Services\Category\CategoryService;
use App\Services\Product\ProductService;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProductController extends Controller
{
    protected $productService;
    protected $categoryService;

    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(Request $request)
    {
        if (!$request->has('q')) {
            $products = $this->productService->index();
        } else {
            $searchTerm = $request->get('q');
            $products = $this->productService->search($searchTerm);
            $products->appends(['q' => $searchTerm]);
        }
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $categories = $this->categoryService->getAll();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateProductRequest  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(CreateProductRequest $request)
    {
        return $this->productService->create($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function show($id)
    {
        $product = $this->productService->getProduct($id);
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function edit($id)
    {
        $product = $this->productService->getProduct($id);
        $categories = $this->categoryService->getAll();
        return view('products.edit', compact(['product', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateProductRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(UpdateProductRequest $request, $id)
    {
        return $this->productService->update($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        return $this->productService->delete($id);
    }

    public function search(Request $request)
    {
        return $this->productService->search($request->get('q'), 10);
    }
}

resources/views/products/create.blade.php
@extends('layouts.app', ['activePage' => 'product', 'titlePage' => __('Create Product')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('products.store') }}" autocomplete="off"
                          class="form-horizontal">
                        @csrf
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Create Product') }}</h4>
                            </div>
                            <div class="card-body ">
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Name') }}" value="{{ old('name') }}"
                                                   required="true" aria-required="true"/>
                                            <span id="name-error" class="error text-danger"
                                                  for="input-name"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Quantity') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('quantity') ? ' has-danger' : '' }}">
                                            <input
                                                class="form-control{{ $errors->has('quantity') ? ' is-invalid' : '' }}"
                                                name="quantity" id="input-quantity" type="number"
                                                placeholder="{{ __('Quantity') }}" value="{{ old('quantity') }}"
                                                required="true" aria-required="true"/>
                                            <span id="quantity-error" class="error text-danger"
                                                  for="input-quantity"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Price') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('price') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                                   name="price" id="input-price" type="number"
                                                   placeholder="{{ __('Price') }}" value="{{ old('price') }}"
                                                   required="true" aria-required="true"/>
                                            <span id="price-error" class="error text-danger"
                                                  for="input-price"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Description') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                            <textarea name="description" id="input-description" cols="30" rows="10"
                                                      placeholder="{{ __('Description') }}"
                                                      class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                            >{{old('description')}}</textarea>
                                            <span id="description-error" class="error text-danger"
                                                  for="input-description"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Category') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('category') ? ' has-danger' : '' }}">
                                            <ul class="category-list list-unstyled">
                                            </ul>
                                            <select name="category" id="input-category"
                                                    class="form-control category-select">
                                                <option value="0">Select category</option>
                                                @foreach($categories as $category)
                                                    <option class="category-option"
                                                            value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                            <span id="category-error" class="error text-danger"
                                                  for="input-category"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Image') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
                                            <input name="image" id="input-image" type="file" accept="image/*"/>
                                            <label for="input-image" class="btn btn-outline-warning mr-4">
                                                Upload file
                                            </label>
                                            <img
                                                src="https://media.istockphoto.com/vectors/no-image-available-icon-vector-id1216251206?b=1&k=20&m=1216251206&s=170667a&w=0&h=z0hxu_BaI_tuMjMneE_APbnx_-R2KGPXgDjdwLw5W7o="
                                                alt="Product image" class="product-img rounded"
                                                width="150"
                                                height="150"
                                            >
                                            <span id="image-error" class="error text-danger"
                                                  for="input-image"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary create-btn">{{ __('Create') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script src="{{asset('/js/product.js')}}"></script>
    @endpush
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app', ['activePage' => 'product', 'titlePage' => __('Create Product')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('products.update', $product->id) }}" autocomplete="off"
                          class="form-horizontal">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="id" value="{{$product->id}}">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Update Product') }}</h4>
                            </div>
                            <div class="card-body ">
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Name') }}" value="{{ $product->name }}"
                                                   required="true" aria-required="true"/>
                                            <span id="name-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Quantity') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('quantity') ? ' has-danger' : '' }}">
                                            <input
                                                class="form-control{{ $errors->has('quantity') ? ' is-invalid' : '' }}"
                                                name="quantity" id="input-quantity" type="number"
                                                placeholder="{{ __('Quantity') }}" value="{{ $product->quantity }}"
                                                required="true" aria-required="true"/>
                                            <span id="quantity-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Price') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('price') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                                   name="price" id="input-price" type="number"
                                                   placeholder="{{ __('Price') }}" value="{{ $product->price  }}"
                                                   required="true" aria-required="true"/>
                                            <span id="price-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Description') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                            <textarea name="description" id="input-description" cols="30" rows="10"
                                                      placeholder="{{ __('Description') }}"
                                                      class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                            >{{$product->description}}</textarea>
                                            <span id="description-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Category') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('category') ? ' has-danger' : '' }}">
                                            <ul class="category-list list-unstyled">
                                                @foreach($product->categories as $category)
                                                    <li class="category-item p-2 rounded bg-dark text-white d-inline-block mr-2 mb-2" data-id="{{$category->id}}">
                                                        <span class="mr-2">{{$category->name}}</span>
                                                        <i class="fa-solid fa-circle-xmark text-danger remove-category-btn"></i>
                                                    </li>
                                                @endforeach
                                            </ul>
                                            <select name="category" id="input-category"
                                                    class="form-control category-select">
                                                <option value="0">Select category</option>
                                                @foreach($categories as $category)
                                                    <option class="category-option"
                                                            value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                            <span id="category-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <label class="col-sm-2 col-form-label">{{ __('Image') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
                                            <input name="image" id="input-image" type="file" accept="image/*"/>
                                            <label for="input-image" class="btn btn-outline-warning mr-4">
                                                Upload file
                                            </label>
                                            <img src="{{asset($product->image_url)}}"
                                                alt="Product image" class="product-img rounded"
                                                width="150"
                                                height="150"
                                            >
                                            <span id="image-error" class="error text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary update-btn">{{ __('Save') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script src="{{asset('/js/product.js')}}"></script>
    @endpush
@endsection

resources/views/products/index.blade.php
@extends('layouts.app', ['activePage' => 'product', 'titlePage' => __('Product List')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <a href="{{route('products.create')}}"
               class="d-inline-flex justify-content-center align-items-center mb-4 rounded bg-dark text-white py-2 px-4">
                <i class="fa-solid fa-plus mr-2"></i>
                New Product
            </a>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Product list</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="text-primary">
                                    <tr class="text-center">
                                        <th>ID</th>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Categories</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($products as $product)
                                        <tr class="text-center product-item" data-id="{{$product->id}}">
                                            <td><a href="{{route('products.show', $product->id)}}">{{$product->id}}</a>
                                            </td>
                                            <td>
{{--                                                <img src="{{asset('images/' . $product->image)}}"--}}
                                                <img src="{{asset($product->image_url)}}"
                                                     alt="Product image"
                                                     class="rounded"
                                                     width="100"
                                                     height="100"
                                                >
                                            </td>
                                            <td>{{$product->name}}</td>
                                            <td>{{$product->description}}</td>
                                            <td>{{$product->quantity}}</td>
                                            <td>{{$product->price}}</td>
                                            <td>
                                                @foreach($product->categories as $category)
                                                    <span class="p-2 rounded bg-dark text-white mr-2 mb-2 d-inline-block">
                                                        {{$category->name}}
                                                    </span>
                                                @endforeach
                                            </td>
                                            <td class="text-right">
                                                <a href="{{route('products.edit', $product->id)}}"
                                                   class="btn btn-primary">Edit</a>
                                                <button type="button" class="btn modal-delete-btn">
                                                    DELETE
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {{$products->links()}}
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">CONFIRM DELETE</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-left">
                    Are you sure you want to delete?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary delete-btn">Delete</button>
                </div>
            </div>
        </div>
    </div>
    @push('js')
        <script src="{{asset('/js/product.js')}}"></script>
    @endpush
@endsection

resources/views/products/show.blade.php
@extends('layouts.app', ['activePage' => 'product', 'titlePage' => __('Product')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <h1 class="mb-4">{{$product->name}}</h1>
            <div class="product-item row">
                <div class="col-md-2">
                    <img src="{{asset($product->image_url)}}" alt="Product image" class="rounded">
                </div>
                <div class="product-info col-md-10">
                    <div class="row mb-2">
                        <div class="col-md-2 text-right">Quantity: </div>
                        <div class="col-md-10">{{$product->quantity}}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-md-2 text-right">Price: </div>
                        <div class="col-md-10">{{$product->price}}</div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-md-2 text-right">Description: </div>
                        <div class="col-md-10">{{$product->description}}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-md-2 text-right">Categories: </div>
                        <div class="col-md-10">
                            @foreach($product->categories as $category)
                                <span class="py-2 px-4 rounded bg-dark text-white mr-2">
                                    {{$category->name}}
                                </span>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection